//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactSorter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactSorter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cary_East {
            get {
                return ResourceManager.GetString("Cary_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cary_NorthEast {
            get {
                return ResourceManager.GetString("Cary_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cary_NorthWest {
            get {
                return ResourceManager.GetString("Cary_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cary_SouthEast {
            get {
                return ResourceManager.GetString("Cary_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cary_SouthWest {
            get {
                return ResourceManager.GetString("Cary_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cary_West {
            get {
                return ResourceManager.GetString("Cary_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Earhart_Men {
            get {
                return ResourceManager.GetString("Earhart_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Earhart_Women {
            get {
                return ResourceManager.GetString("Earhart_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstStreetCentral_Men {
            get {
                return ResourceManager.GetString("FirstStreetCentral_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstStreetCentral_Women {
            get {
                return ResourceManager.GetString("FirstStreetCentral_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstStreetEast_Men {
            get {
                return ResourceManager.GetString("FirstStreetEast_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstStreetEast_Women {
            get {
                return ResourceManager.GetString("FirstStreetEast_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstStreetWest_Men {
            get {
                return ResourceManager.GetString("FirstStreetWest_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstStreetWest_Women {
            get {
                return ResourceManager.GetString("FirstStreetWest_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Harrison_Men {
            get {
                return ResourceManager.GetString("Harrison_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Harrison_Women {
            get {
                return ResourceManager.GetString("Harrison_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hawkins_Men {
            get {
                return ResourceManager.GetString("Hawkins_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hawkins_Women {
            get {
                return ResourceManager.GetString("Hawkins_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hillenbrand_Men {
            get {
                return ResourceManager.GetString("Hillenbrand_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hillenbrand_Women {
            get {
                return ResourceManager.GetString("Hillenbrand_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hilltop_Men {
            get {
                return ResourceManager.GetString("Hilltop_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hilltop_Women {
            get {
                return ResourceManager.GetString("Hilltop_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HonorsNorth_Men {
            get {
                return ResourceManager.GetString("HonorsNorth_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HonorsNorth_Women {
            get {
                return ResourceManager.GetString("HonorsNorth_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HonorsSouth_Men {
            get {
                return ResourceManager.GetString("HonorsSouth_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HonorsSouth_Women {
            get {
                return ResourceManager.GetString("HonorsSouth_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string McCutcheon_Men {
            get {
                return ResourceManager.GetString("McCutcheon_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string McCutcheon_Women {
            get {
                return ResourceManager.GetString("McCutcheon_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Meredith_NorthEast {
            get {
                return ResourceManager.GetString("Meredith_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Meredith_NorthWest {
            get {
                return ResourceManager.GetString("Meredith_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Meredith_SouthEast {
            get {
                return ResourceManager.GetString("Meredith_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Meredith_SouthWest {
            get {
                return ResourceManager.GetString("Meredith_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Owen_Men {
            get {
                return ResourceManager.GetString("Owen_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Owen_Women {
            get {
                return ResourceManager.GetString("Owen_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shreve_Men {
            get {
                return ResourceManager.GetString("Shreve_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shreve_Women {
            get {
                return ResourceManager.GetString("Shreve_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tarkington {
            get {
                return ResourceManager.GetString("Tarkington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ThirdStreet_Men {
            get {
                return ResourceManager.GetString("ThirdStreet_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ThirdStreet_Women {
            get {
                return ResourceManager.GetString("ThirdStreet_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Wiley_Men {
            get {
                return ResourceManager.GetString("Wiley_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Wiley_Women {
            get {
                return ResourceManager.GetString("Wiley_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Windsor_Duhme {
            get {
                return ResourceManager.GetString("Windsor_Duhme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Windsor_Shealy {
            get {
                return ResourceManager.GetString("Windsor_Shealy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Windsor_Vawter {
            get {
                return ResourceManager.GetString("Windsor_Vawter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Windsor_Walter {
            get {
                return ResourceManager.GetString("Windsor_Walter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Windsor_Wood {
            get {
                return ResourceManager.GetString("Windsor_Wood", resourceCulture);
            }
        }
    }
}
